import {useEffect,useState} from 'react';
import {Activity, ArrowDownToLine, ArrowUpRight, Clock, Database, Globe2, Radio, ShieldCheck, X} from 'lucide-react';

type Injury={external_id:string;player:string;team:string|null;team_id:string;league:string;status:string;detail:string;reported_at:string|null;source_url:string|null;fresh:boolean;last_checked_at:string|null;source:string};
type SideContext={hours_since_prior_start:number|null;back_to_back_schedule:boolean;prior_event:string|null;prior_source_url:string|null;schedule_fresh:boolean;injuries:Injury[];injury_coverage:string};
type SportEvent={external_id:string;league:string;name:string;starts_at:string;home:{id:string;name:string;score:string|null;record:string|null;statistics?:{name:string;label:string;value:string}[];player_leaders?:{metric:string;player:string;value:string}[]};away:{id:string;name:string;score:string|null;record:string|null;statistics?:{name:string;label:string;value:string}[];player_leaders?:{metric:string;player:string;value:string}[]};state:string;status:string;completed:boolean;venue:string|null;location:string;match_type:string|null;source_url:string|null;fetched_at:string;last_checked_at:string|null;fresh:boolean;context?:{home:SideContext;away:SideContext}};
type News={external_id:string;headline:string;description:string;league:string;source:string;source_url:string;published_at:string|null;fresh:boolean;injury_related:boolean};
type Feed={id:string;league:string;category:string;status:string;fresh:boolean;last_success:string|null;last_attempt:string|null;error:string|null;url:string};
type LiveData={enabled:boolean;feeds:Feed[];events:SportEvent[];results:SportEvent[];news:News[];injuries:Injury[];observation_count:number;forecast_status:string;limitations:string[]};
const when=(v:string|null)=>v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Unknown';
const source=(v:string)=>v.startsWith('bbc:')?'BBC Sport':'ESPN';
function Link({url,label='View source'}:{url:string|null;label?:string}){return url?<a className="source-link" href={url} target="_blank" rel="noopener noreferrer">{label}<ArrowUpRight size={13}/></a>:<span className="muted">Source link unavailable</span>}
export default function LiveResearch(){
 const [data,setData]=useState<LiveData|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('Fixtures & context'),[league,setLeague]=useState('All sports'),[selected,setSelected]=useState<SportEvent|null>(null);
 useEffect(()=>{let mounted=true;let current:AbortController|null=null;async function poll(){current?.abort();current=new AbortController();const timeout=setTimeout(()=>current?.abort(),10000);try{const r=await fetch('/api/live',{signal:current.signal});if(!r.ok)throw Error();const next=await r.json();if(mounted){setData(next);setError('')}}catch{if(mounted)setError('Live research API unavailable. Cached observations may be stale.')}finally{clearTimeout(timeout)}}poll();const interval=setInterval(poll,30000);return()=>{mounted=false;clearInterval(interval);current?.abort()}},[]);
 const leagues=['All sports',...new Set(data?.feeds.map(f=>f.league).filter(l=>l!=='All sports')||[])];
 const filter=<T extends {league:string}>(rows:T[])=>rows.filter(r=>league==='All sports'||r.league===league||(tab==='News wire'&&r.league==='All sports'));
 const feeds=filter(data?.feeds||[]), events=filter(data?.events||[]),news=filter(data?.news||[]),injuries=filter(data?.injuries||[]),results=filter(data?.results||[]);
 const healthy=(data?.feeds||[]).filter(f=>f.fresh).length;
 const freshness=(fresh:boolean)=><span className={`tag ${fresh&&!error?'live-tag':'amber'}`}>{fresh&&!error?'RECENTLY CHECKED':'STALE / UNAVAILABLE'}</span>;
 function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='sourced-sports-observations.json';a.click();URL.revokeObjectURL(url)}
 return <div className="live-research">{error&&<div className="error" role="alert">{error}</div>}<div className="live-toolbar"><div><span className="dot"/>{data?.enabled?'Collector enabled · five-minute feed polling · 30-second display refresh':'Live collector disabled or starting'}</div><button className="outline" disabled={!data} onClick={exportData}><ArrowDownToLine size={14}/>Export observations</button></div>
 <div className="stats-grid"><div className="stat"><div>LIVE FEED HEALTH<Radio size={16}/></div><strong className="accent">{error?'—':`${healthy} / ${data?.feeds.length??'—'}`}</strong><p>Recent, successful feed checks</p></div><div className="stat"><div>TRACKED EVENTS<Activity size={16}/></div><strong>{data?data.events.length+data.results.length:'—'}</strong><p>Public schedules and observed results</p></div><div className="stat"><div>STORED OBSERVATIONS<Database size={16}/></div><strong>{data?.observation_count??'—'}</strong><p>Append-only source revisions</p></div><div className="stat"><div>LIVE FORECASTS<ShieldCheck size={16}/></div><strong>Unavailable</strong><p>No validated live model deployed</p></div></div>
 <div className="research-note live-note"><Globe2 size={22}/><div><h3>Source evidence, with explicit gaps</h3><p>Reported injuries are not medical confirmations. Schedule spacing is a rest proxy, not measured fatigue. Travel distance, player workloads, and complete injury coverage are currently unknown. No missing values are invented.</p></div></div>
 <div className="live-controls"><div className="live-tabs">{['Fixtures & context','Reported injuries','News wire','Feed health','Observed results'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><select aria-label="Filter live sport" value={league} onChange={e=>setLeague(e.target.value)}>{leagues.map(l=><option key={l}>{l}</option>)}</select></div>
 {tab==='Fixtures & context'&&<div className="live-event-grid">{events.map(e=><section className="panel live-event" key={`${e.league}:${e.external_id}`}><div className="live-event-top"><span className="tag">{e.league}</span>{freshness(e.fresh)}</div><h2>{e.away.name}<span>at {e.home.name}</span></h2><p><Clock size={12}/>{when(e.starts_at)} · {e.status}</p><div className="context-preview">{(['away','home'] as const).map(s=><div key={s}><span>{s==='home'?'Home':'Away'} · schedule interval</span><b>{e.context?.[s].hours_since_prior_start!=null?`${e.context[s].hours_since_prior_start} hours`:'Unknown'}</b><small>{e.context?.[s].back_to_back_schedule?'Short interval ≤ 30 hours':'Since prior known completed event start'}</small></div>)}</div><div className="live-event-footer"><Link url={e.source_url}/><button className="text-button" onClick={()=>setSelected(e)}>Inspect context →</button></div></section>)}{!events.length&&<Empty title="No live fixtures available" text="The collector needs a reachable scoreboard feed. Check Feed health for source-specific status; no demo fixtures appear here."/>}</div>}
 {tab==='News wire'&&<div className="news-grid">{news.map(n=><article className="panel news-card" key={`${n.source}:${n.external_id}`}><div className="live-event-top"><span className="tag">{source(n.source)} · {n.league}</span>{n.injury_related&&<span className="tag amber">INJURY-RELATED COVERAGE</span>}</div><h2><a href={n.source_url} target="_blank" rel="noopener noreferrer">{n.headline}</a></h2><p>{n.description}</p><div className="live-event-footer"><span>Published {when(n.published_at)}</span>{freshness(n.fresh)}</div><Link url={n.source_url} label="Read original report"/></article>)}{!news.length&&<Empty title="No source articles available" text="ESPN and BBC Sport reports appear here only after a successful feed response."/>}</div>}
 {tab==='Reported injuries'&&<section className="panel"><div className="panel-title"><div><h2>Provider-reported player injuries</h2><p>Coverage is partial. No reports does not mean a team is healthy.</p></div></div><div className="table-wrap"><table><thead><tr><th>PLAYER / TEAM</th><th>REPORTED STATUS</th><th>REPORT TIME</th><th>FEED CHECK</th><th>SOURCE</th></tr></thead><tbody>{injuries.map(i=><tr key={`${i.source}:${i.external_id}`}><td><b>{i.player}</b><small>{i.team??'Unknown team'} · {i.league}</small></td><td>{i.status}<small>{i.detail}</small></td><td>{when(i.reported_at)}</td><td>{freshness(i.fresh)}</td><td><Link url={i.source_url}/></td></tr>)}</tbody></table></div>{!injuries.length&&<Empty title="Structured injury coverage unavailable" text="Check Feed health for errors. Injury-related news is available separately when news feeds work; it is never converted into confirmed player status."/>}</section>}
 {tab==='Feed health'&&<section className="panel"><div className="panel-title"><div><h2>Public source connectivity</h2><p>Errors retain historical observations and trigger exponential retry delays.</p></div></div><div className="table-wrap"><table><thead><tr><th>PROVIDER / LEAGUE</th><th>DATA TYPE</th><th>STATE</th><th>LAST SUCCESS</th><th>DIAGNOSTIC</th></tr></thead><tbody>{feeds.map(f=><tr key={f.id}><td><b>{source(f.id)}</b><small>{f.league}</small></td><td>{f.category}</td><td>{freshness(f.fresh)}<small>{f.status}</small></td><td>{when(f.last_success)}</td><td className="diagnostic">{f.error??(f.status==='waiting'?'Waiting for first collection':'No error reported')}</td></tr>)}</tbody></table></div></section>}
 {tab==='Observed results'&&<section className="panel"><div className="panel-title"><div><h2>Source-reported completed events</h2><p>Actual source observations; not merged into demo forecast scores.</p></div></div><div className="table-wrap"><table><thead><tr><th>EVENT</th><th>REPORTED SCORE</th><th>STATUS</th><th>DATE</th><th>SOURCE</th></tr></thead><tbody>{results.map(e=><tr key={`${e.league}:${e.external_id}`} onClick={()=>setSelected(e)} tabIndex={0} onKeyDown={key=>{if(key.key==='Enter')setSelected(e)}} aria-label={`Inspect result for ${e.name}`}><td><b>{e.away.name} at {e.home.name}</b><small>{e.league}</small></td><td>{e.away.score??'—'} – {e.home.score??'—'}</td><td>{e.status}<small>{e.fresh&&!error?'Recently checked':'Stale observation'}</small></td><td>{when(e.starts_at)}</td><td><Link url={e.source_url}/></td></tr>)}</tbody></table></div>{!results.length&&<Empty title="No completed results collected" text="Recent completed events will appear when scoreboard feeds return verified source data."/>}</section>}
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal live-modal" role="dialog" aria-modal="true" aria-label="Source event context" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close context" onClick={()=>setSelected(null)}><X size={20}/></button><div className="eyebrow">SOURCED EVENT CONTEXT</div><h2>{selected.name}</h2><p>{when(selected.starts_at)} · {selected.league}</p><dl><dt>Venue</dt><dd>{selected.venue??'Unknown'}</dd><dt>Location</dt><dd>{selected.location||'Unknown'}</dd><dt>Match type</dt><dd>{selected.match_type??'Unknown'}</dd><dt>Last source check</dt><dd>{when(selected.last_checked_at)}</dd></dl>{(['home','away'] as const).map(s=><div className="context-detail" key={s}><h3>{selected[s].name}</h3><p>Provider record: {selected[s].record??'Unknown'}</p><h4>Source-supplied scoreboard statistics</h4>{selected[s].statistics?.length?<div className="source-stats">{selected[s].statistics?.map(stat=><span key={stat.name}><b>{stat.name} ({stat.label})</b> {stat.value}</span>)}</div>:<p>Statistics not supplied for this event.</p>}<h4>Source-supplied player leaders</h4>{selected[s].player_leaders?.length?selected[s].player_leaders?.map((l,i)=><p key={i}>{l.player} · {l.metric}: {l.value}</p>):<p>Player statistics not supplied for this event.</p>}<p>Schedule interval: {selected.context?.[s].hours_since_prior_start??'Unknown'} {selected.context?.[s].hours_since_prior_start!=null?'hours between event starts':''}</p><p>Prior event: {selected.context?.[s].prior_event??'Not present in collected window'}</p><p>Schedule evidence: {selected.context?.[s].schedule_fresh?'recently checked':'stale or incomplete'}</p><p>Injury coverage: {selected.context?.[s].injury_coverage}</p>{selected.context?.[s].injuries.map(i=><p key={i.external_id}>{i.player}: {i.status} · Reported {when(i.reported_at)}</p>)}</div>)}<div className="research-note"><p>Travel and player workloads: unknown. Physiological fatigue: not measured. No live probability estimate is generated from this incomplete context.</p></div><Link url={selected.source_url}/></section></div>}
 </div>
}
function Empty({title,text}:{title:string;text:string}){return <div className="empty live-empty"><Radio size={28}/><h3>{title}</h3><p>{text}</p></div>}
