import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowDownToLine, ArrowRight, BarChart3, Check, CircleHelp, Database, FileText, FlaskConical, Globe2, Layers3, Radio, RefreshCw, Search, ShieldCheck, TrendingUp, X} from 'lucide-react';
import {Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import './style.css';

type Forecast = {id:string; event_id:string; home:string; away:string; home_code:string; away_code:string; league:string; probability:number; uncertainty:number; published_at:string; starts_at:string; hash:string; outcome:number|null; model_version:string; feature_snapshot:Record<string,number>; target:string};
type Metrics = {total:number; settled:number; pending:number; brier:number|null; log_loss:number|null; accuracy:number|null; calibration:{bucket:string;predicted:number|null;observed:number|null;count:number}[];timeline:{date:string;brier:number;baseline:number}[]};
type Overview = {metrics:Metrics;forecasts:Forecast[];integrity:boolean;walk_forward:{train_count:number;test_count:number;test_from:string;test_to:string;model_brier:number;prior_brier:number}[]};
type Event = {id:string;home:string;away:string;league:string;starts_at:string};
const pct = (n:number) => `${(n*100).toFixed(1)}%`;
const date = (s:string) => new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const pages = ['Overview','Forecast ledger','Model research','Data sources','Methodology'];
const icons = [Layers3,FileText,FlaskConical,Database,CircleHelp];
function App(){
 const [page,setPage]=useState('Overview'),[sport,setSport]=useState('All sports'),[search,setSearch]=useState(''),[overview,setOverview]=useState<Overview|null>(null),[rows,setRows]=useState<Forecast[]>([]),[events,setEvents]=useState<Event[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[selected,setSelected]=useState<Forecast|null>(null),[updated,setUpdated]=useState('');
 async function load(){setLoading(true);setError('');try{const responses=await Promise.all(['/api/overview','/api/forecasts','/api/events'].map(p=>fetch(p)));if(responses.some(r=>!r.ok))throw new Error('API unavailable');const [o,r,e]=await Promise.all(responses.map(r=>r.json()));setOverview(o);setRows(r);setEvents(e);setUpdated(new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));}catch{setError('The research API is unavailable. Start the backend and refresh to reconnect.');}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const filtered=rows.filter(r=>(sport==='All sports'||r.league===sport)&&(page!=='Forecast ledger'||`${r.home} ${r.away} ${r.event_id}`.toLowerCase().includes(search.toLowerCase())));
 const m=overview?.metrics;
 const pending=filtered.filter(r=>r.outcome===null);
 function exportLedger(){const blob=new Blob([JSON.stringify(filtered,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='research-demo-ledger.json';a.click();URL.revokeObjectURL(url)}
 const table=(limit?:number)=><div className="table-wrap"><table><thead><tr><th>EVENT / HOME TEAM</th><th>LEAGUE</th><th>HOME WIN PROB.</th><th>OBSERVED RESULT</th><th>PUBLISHED</th><th>AUDIT RECORD</th></tr></thead><tbody>{filtered.slice(0,limit).map(r=><tr key={r.id} onClick={()=>setSelected(r)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')setSelected(r)}} aria-label={`View forecast for ${r.home} vs ${r.away}`}><td><b>{r.home} <span className="muted">vs</span> {r.away}</b><small>{r.event_id}</small></td><td><span className="tag">{r.league}</span></td><td><span className="mono">{pct(r.probability)}</span><div className="mini-bar"><i style={{width:pct(r.probability)}}/></div></td><td><span className={`result ${r.outcome===null?'pending':r.outcome?'positive':'neutral'}`}>{r.outcome===null?'Pending':r.outcome?'Home win':'Home non-win'}</span></td><td>{date(r.published_at)}</td><td><span className="hash"><ShieldCheck size={13}/>{r.hash.slice(0,10)}</span></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty">No forecasts match these filters.</div>}</div>;
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Overview')}}><div className="brand-icon"><Activity size={22}/></div><span>COURTSIDE<small>RESEARCH TERMINAL</small></span></a><div className="workspace-label">WORKSPACE <span>01</span></div><nav>{pages.map((p,i)=>{const Icon=icons[i];return <button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}><Icon size={18}/>{p}{p==='Overview'&&<span className="nav-dot"/>}</button>})}</nav><div className="side-card"><div className="tiny"><FlaskConical size={14}/> RESEARCH ENVIRONMENT</div><h4>Evidence before confidence.</h4><p>Evaluate forecasts. Preserve every outcome. Let the data speak.</p><button onClick={()=>setPage('Methodology')}>Read our methodology <ArrowRight size={14}/></button></div><div className="side-bottom"><span className="avatar">CR</span><div>Local workspace<small>Research access · read only</small></div><ShieldCheck size={16}/></div></aside>
 <main><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <b>{page}</b></div><div className="top-right"><span className="demo-chip"><span/> DEMO ENVIRONMENT</span><span className="top-divider"/><span className="avatar small">CR</span></div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">SPORTS INTELLIGENCE / RESEARCH</div><h1>{page==='Overview'?'A clearer view of the game.':page}</h1><p>{page==='Overview'?'Independent forecasts. Measurable uncertainty. An auditable record.':page==='Forecast ledger'?'Every forecast, every outcome. Nothing omitted.':page==='Model research'?'Measure predictive quality across the complete sample.':page==='Data sources'?'Know where every observation comes from.':'The assumptions behind the numbers, made explicit.'}</p></div><button className="outline" onClick={load} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/> {loading?'Refreshing':'Refresh data'}</button></div>
 <div className="demo-banner"><FlaskConical size={18}/><div><b>Simulated data. Real research workflow.</b><span>All forecasts and evaluation results below are synthetic. This is not live sports information.</span></div><span className="banner-tag">DEMO MODE</span></div>
 {error&&<div role="alert" className="error">{error}</div>}
 {(page==='Overview'||page==='Forecast ledger')&&<div className="filterbar"><div className="segmented">{['All sports','NBA','NHL','Premier League'].map(s=><button key={s} onClick={()=>setSport(s)} className={sport===s?'selected':''}>{s==='Premier League'?'Football':s}</button>)}</div><div className="freshness"><span className="dot"/> {updated?`Loaded ${updated}`:'Connecting to research API'}</div></div>}
 {page==='Overview'&&<><div className="stats-grid"><Stat label="FORECASTS RECORDED" value={m?String(m.total):'—'} detail="Entire synthetic dataset" icon={<Layers3 size={16}/>}/><Stat label="BRIER SCORE" value={m?.brier?.toFixed(3)??'—'} detail="Lower is better · baseline 0.250" icon={<TrendingUp size={16}/>}/><Stat label="LOG LOSS" value={m?.log_loss?.toFixed(3)??'—'} detail="Lower is better · binary outcome" icon={<BarChart3 size={16}/>}/><Stat label="AUDIT INTEGRITY" value={overview?(overview.integrity?'Verified':'Failed'):'—'} detail="SHA-256 records + chained audit log" icon={<ShieldCheck size={16}/>} accent/></div>
 <div className="two-col"><section className="panel chart-panel"><PanelTitle title="Predictive performance" sub="Cumulative Brier score · all sports" extra={<span className="tag">Full history</span>}/><div className="chart-legend"><span><i className="legend-line teal"/> Illustrative baseline model</span><span><i className="legend-line gray"/> 50% reference</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={m?.timeline||[]} margin={{top:10,right:10,left:-22,bottom:0}}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#65dfc3" stopOpacity={.2}/><stop offset="100%" stopColor="#65dfc3" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#25303c" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="date" tickFormatter={date} minTickGap={50} tick={{fill:'#8190a1',fontSize:11}} axisLine={false} tickLine={false}/><YAxis domain={[0,.6]} tick={{fill:'#8190a1',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#161e28',border:'1px solid #30404e',borderRadius:8}} labelFormatter={v=>date(String(v))}/><Area isAnimationActive={false} type="monotone" dataKey="brier" stroke="#65dfc3" strokeWidth={2} fill="url(#fill)"/><Area isAnimationActive={false} dataKey="baseline" stroke="#69788a" strokeDasharray="5 5" fill="none"/></AreaChart></ResponsiveContainer></div><div className="chart-foot"><span>{m?.settled??0} evaluated observations</span><span>Untrained illustrative model · not validated</span></div></section>
 <section className="panel calibration-panel"><PanelTitle title="Calibration check" sub="Forecast probability vs. observed frequency"/><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={m?.calibration.filter(x=>x.count)||[]} margin={{top:16,right:12,left:-24,bottom:0}}><CartesianGrid stroke="#25303c" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="bucket" tick={{fill:'#8190a1',fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={[0,1]} tickFormatter={v=>`${v*100}%`} tick={{fill:'#8190a1',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#161e28',border:'1px solid #30404e',borderRadius:8}}/><Line isAnimationActive={false} dataKey="predicted" stroke="#69788a" strokeDasharray="5 5" dot={false}/><Line isAnimationActive={false} dataKey="observed" stroke="#a5a2ef" strokeWidth={2} dot={{fill:'#a5a2ef',r:4}}/></LineChart></ResponsiveContainer></div><div className="chart-foot"><span><i className="legend-line purple"/> Observed</span><span>Small samples are inconclusive</span></div></section></div>
 <div className="section-heading"><div><h2>Upcoming research forecasts <span>{pending.length}</span></h2><p>Illustrative projections, with uncertainty kept in view.</p></div><button className="text-button" onClick={()=>setPage('Forecast ledger')}>View ledger <ArrowRight size={15}/></button></div><div className="forecast-grid">{pending.slice(0,3).map((r,i)=><button className="forecast-card" key={r.id} onClick={()=>setSelected(r)}><div className="forecast-top"><span className="tag">{r.league}</span><span>{date(r.starts_at)} <span className="muted">· Synthetic</span></span></div><div className="matchup"><span className={`team-logo tone-${i}`}>{r.home_code}</span><div><h3>{r.home}</h3><p>vs {r.away}</p></div><ArrowRight size={17}/></div><div className="forecast-numbers"><div><small>HOME WIN PROBABILITY</small><strong>{pct(r.probability)}</strong></div><div className="range"><small>ILLUSTRATIVE RANGE</small><b>{pct(Math.max(0,r.probability-r.uncertainty))} – {pct(Math.min(1,r.probability+r.uncertainty))}</b></div></div><div className="probability-bar"><i style={{width:pct(r.probability)}}/></div><div className="forecast-footer"><span><ShieldCheck size={12}/> Record preserved</span><span>Inspect forecast ↗</span></div></button>)}{pending.length===0&&<div className="empty">No pending demo forecasts for this sport.</div>}</div>
 <section className="panel ledger-panel"><PanelTitle title="Recent forecast ledger" sub="All results retained · synthetic observations" extra={<button className="text-button" onClick={()=>setPage('Forecast ledger')}>View all <ArrowRight size={14}/></button>}/>{table(5)}</section><div className="bottom-grid"><div className="health-strip"><span className="health-icon"><Radio size={20}/></span><div><b>Research system status</b><p>Local database connected. Live providers not configured.</p></div><button className="text-button" onClick={()=>setPage('Data sources')}>Inspect sources <ArrowRight size={14}/></button></div><div className="health-strip"><span className="health-icon purple-icon"><FlaskConical size={20}/></span><div><b>Model baseline v1</b><p>Illustrative coefficients. No trained champion deployed.</p></div></div></div></>}
 {page==='Forecast ledger'&&<section className="panel"><PanelTitle title={`${filtered.length} immutable forecasts`} sub="Demo ledger · select a row to inspect its original record" extra={<button className="outline" onClick={exportLedger}><ArrowDownToLine size={14}/> Export JSON</button>}/><div className="searchbar"><Search size={16}/><input aria-label="Search forecasts" placeholder="Search team or event ID…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{table()}</section>}
 {page==='Model research'&&<><div className="stats-grid"><Stat label="EVALUATED SAMPLE" value={String(m?.settled??0)} detail="Synthetic observations only" icon={<Layers3 size={16}/>}/><Stat label="BRIER SCORE" value={m?.brier?.toFixed(3)??'—'} detail="Compare against 0.250 reference" icon={<BarChart3 size={16}/>}/><Stat label="LOG LOSS" value={m?.log_loss?.toFixed(3)??'—'} detail="Probabilistic error" icon={<TrendingUp size={16}/>}/><Stat label="CLASSIFICATION ACCURACY" value={m?.accuracy!=null?pct(m.accuracy):'—'} detail="Threshold 50% · binary target" icon={<Check size={16}/>}/></div><section className="panel"><PanelTitle title="Calibration by probability bucket" sub="Empty buckets are not treated as successful observations"/><div className="table-wrap"><table><thead><tr><th>BUCKET</th><th>SAMPLE</th><th>MEAN FORECAST</th><th>OBSERVED FREQUENCY</th></tr></thead><tbody>{m?.calibration.map(b=><tr key={b.bucket}><td>{b.bucket}</td><td>{b.count}</td><td>{b.predicted===null?'—':pct(b.predicted)}</td><td>{b.observed===null?'—':pct(b.observed)}</td></tr>)}</tbody></table></div></section><section className="panel walk-forward"><PanelTitle title="Chronological walk-forward benchmark" sub="Expanding training window · historical home-win frequency challenger · demo only"/><div className="table-wrap"><table><thead><tr><th>TEST WINDOW</th><th>TRAIN SAMPLE</th><th>TEST SAMPLE</th><th>MODEL BRIER</th><th>HISTORICAL PRIOR BRIER</th></tr></thead><tbody>{overview?.walk_forward.map(f=><tr key={f.test_from}><td>{date(f.test_from)} – {date(f.test_to)}</td><td>{f.train_count}</td><td>{f.test_count}</td><td>{f.model_brier.toFixed(3)}</td><td>{f.prior_brier.toFixed(3)}</td></tr>)}</tbody></table></div></section><div className="research-note"><FlaskConical size={22}/><div><h3>No validated production model</h3><p>The baseline uses fixed synthetic ratings and a logistic transform. Its uncertainty range is illustrative, not a statistical confidence interval. The walk-forward benchmark fits a historical-frequency challenger only on earlier, available results. Feature-model retraining and promotion gates require real historical data and are not implemented in this initial version.</p></div></div></>}
 {page==='Data sources'&&<><div className="source-grid"><section className="panel source-card"><div className="source-icon"><Database size={24}/></div><span className="tag">AVAILABLE</span><h2>Synthetic provider</h2><p>NBA, NHL and football fixtures, ratings, and outcomes generated for interface and integrity testing.</p><dl><dt>Mode</dt><dd>Demo only</dd><dt>Forecast records</dt><dd>{m?.total??'—'}</dd><dt>Live information</dt><dd>None</dd></dl></section><section className="panel source-card"><div className="source-icon football"><Globe2 size={24}/></div><span className="tag amber">IMPORT ADAPTER</span><h2>FotMob · football</h2><p>Import fixtures from user-supplied matches JSON. These fixtures stay separate from the synthetic forecast ledger.</p><dl><dt>Imported fixtures</dt><dd>{events.length}</dd><dt>Live connection</dt><dd>Not verified</dd><dt>Forecasting</dt><dd>Not enabled</dd></dl></section></div><section className="panel"><PanelTitle title="Imported football fixtures" sub="FotMob imports are user-supplied; provenance is recorded separately"/>{events.length?<div className="table-wrap"><table><thead><tr><th>EVENT</th><th>LEAGUE</th><th>KICKOFF</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{e.home} vs {e.away}</td><td>{e.league}</td><td>{new Date(e.starts_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="empty"><Database size={28}/><h3>No FotMob fixtures imported</h3><p>Use the documented server-side import command with your authorized JSON export, then refresh.</p></div>}</section></>}
 {page==='Methodology'&&<div className="method-grid">{[['01','Provenance first','Every forecast records its source, model version, feature timestamp, and original features. Synthetic data is labeled and kept separate from imported fixtures.'],['02','Transparent baseline','Home-win probability uses a logistic function of synthetic rating difference and an illustrative home adjustment. Football draws count as non-wins. No fitted or validated coefficients are claimed.'],['03','Time-aware records','Feature timestamps must precede publication; publication must precede the scheduled event. Results must be sourced and recorded after the start.'],['04','Append-only history','Database triggers block forecast, result and audit edits and deletion. SHA-256 hashes and a chained event log expose record modification; database access still requires operational protection.'],['05','Full-sample evaluation','Brier score, log loss and calibration use every resolved forecast. Pending events are reported separately. Charts describe synthetic data, not real-world predictive ability.'],['06','Research, with limits','Forecasts are probabilistic and can be wrong. This platform does not recommend wagers. A real provider, validated historical data and out-of-sample evaluation are prerequisites for production forecasting.']].map(([n,t,d])=><section className="panel method-card" key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></section>)}</div>}
 <footer><span><Activity size={13}/> COURTSIDE RESEARCH</span><p>Probabilistic forecasts. Transparent methods. No wagering recommendations.</p><span>DEMO · v0.1</span></footer></div></main>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Forecast audit record" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close details" onClick={()=>setSelected(null)}><X size={20}/></button><div className="eyebrow">IMMUTABLE DEMO RECORD</div><h2>{selected.home} vs {selected.away}</h2><p>{selected.target}</p><div className="modal-value">{pct(selected.probability)} <small>home-win probability</small></div><dl><dt>Model</dt><dd>{selected.model_version}</dd><dt>Published</dt><dd>{new Date(selected.published_at).toLocaleString()}</dd><dt>Outcome</dt><dd>{selected.outcome===null?'Pending':selected.outcome?'Home win':'Home non-win'}</dd><dt>Provider</dt><dd>Synthetic v1</dd></dl><h4>Original feature snapshot</h4><pre>{JSON.stringify(selected.feature_snapshot,null,2)}</pre><h4>SHA-256 prediction hash</h4><pre>{selected.hash}</pre><p className="muted">Illustrative model and uncertainty. Not a validated real-world forecast.</p></section></div>}
 </div>
}
function Stat({label,value,detail,icon,accent=false}:{label:string;value:string;detail:string;icon:React.ReactNode;accent?:boolean}){return <section className="stat"><div>{label}{icon}</div><strong className={accent?'accent':''}>{value}</strong><p>{detail}</p></section>}
function PanelTitle({title,sub,extra}:{title:string;sub:string;extra?:React.ReactNode}){return <div className="panel-title"><div><h2>{title}</h2><p>{sub}</p></div>{extra}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
