import {useEffect,useState} from 'react';
type Row={id:string;hash:string;event:string;league:string;kind:string;description:string;threshold:number|null;starts_at:string;published_at:string;probabilities:{yes:number;no:number};predicted_outcome:'yes'|'no';estimated_probability:number;league_games:number;team_games:{home:number;away:number};uncertainty:string;score_scope:string;result:null|{correct:boolean;home_score:string;away_score:string};training_data_hash:string;model_version:string;empirical_frequency_interval?:number[];evidence_warning?:string;research_context?:{numerical_use:string;schedule_and_injuries:Record<string,{hours_since_prior_start:number|null;injury_coverage:string}>;external_sources:{name:string;url:string;use:string;fetched_at:string}[]}};
type Metrics={wins:number;losses:number;pending:number;scored:number;accuracy:number|null};
type Evidence={league:string;target:string;model_version:string;description:string;metrics:Metrics&{accuracy_interval:number[]|null;brier:number|null;log_loss:number|null};distinct_matches:number;mean_scored_probability:number|null;calibration_gap:number|null;status:string};
type Data={evidence_report?:Evidence[];forecasts:Row[];integrity:boolean;policy:string;exclusions?:{event:string;league:string;reason:string}[];monitoring?:Record<string,{pause_new_forecasts:boolean}>};
const pct=(v:number|null)=>v===null?'—':`${(v*100).toFixed(1)}%`;
export default function ScoreForecasts(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[kind,setKind]=useState('all'),[minimum,setMinimum]=useState('all'),[status,setStatus]=useState('all'),[selected,setSelected]=useState<Row|null>(null),[league,setLeague]=useState('all'),[threshold,setThreshold]=useState('all'),[view,setView]=useState('forecasts'),[limit,setLimit]=useState(40);
 useEffect(()=>{async function load(){try{const r=await fetch('/api/score-forecasts');if(!r.ok)throw Error();setData(await r.json());setError('')}catch{setError('Score forecast tracker unavailable.')}}load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>setLimit(40),[kind,minimum,status,league,threshold]);
 useEffect(()=>{if(!selected)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[selected]);
 const cohort=(data?.forecasts||[]).filter(r=>(kind==='all'||r.kind===kind)&&(minimum==='all'||r.estimated_probability>=Number(minimum)/100)&&(league==='all'||r.league===league)&&(threshold==='all'||String(r.threshold)===threshold));
 const leagues=['NBA','NFL','NHL','MLB','Premier League','Champions League'];
 const thresholds=Array.from(new Set((data?.forecasts||[]).filter(r=>(league==='all'||r.league===league)&&(kind==='all'||r.kind===kind)).map(r=>String(r.threshold)))).sort((a,b)=>Number(a)-Number(b));
 const scored=cohort.filter(r=>r.result);const wins=scored.filter(r=>r.result?.correct).length;
 const m:Metrics={wins,losses:scored.length-wins,pending:cohort.length-scored.length,scored:scored.length,accuracy:scored.length?wins/scored.length:null};
 const rows=cohort.filter(r=>status==='all'||(status==='pending'?!r.result:!!r.result));
 function exportLedger(){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='score-research-ledger.json';a.click();URL.revokeObjectURL(url)}
 return <section><div className="prediction-disclosure"><div><b>Experimental score-event forecasts</b><p>Totals, home margins, and both teams scoring. A 60% model estimate is not demonstrated 60% accuracy. Fixed research thresholds are not bookmaker lines. All eligible forecasts remain in the ledger.</p></div></div>{error&&<div className="error">{error}</div>}{data?.monitoring&&Object.entries(data.monitoring).filter(([,m])=>m.pause_new_forecasts).map(([k])=><div className="error" key={k}>{k}: new forecasts paused for review after underperforming the uniform baseline. Recorded outcomes continue to be scored.</div>)}
 <div className="stats-grid tracker-stats">{[['WINS · CORRECT',m.wins],['LOSSES · INCORRECT',m.losses],['PENDING',m.pending],['OBSERVED ACCURACY',pct(m.accuracy)]].map(([title,value])=><section className="stat" key={title}><div>{title}</div><strong>{value}</strong><p>{m.scored} scored · selected type and probability cohort</p></section>)}</div>
 <div className="live-tabs"><button className={view==='forecasts'?'selected':''} onClick={()=>setView('forecasts')}>Forecasts</button><button className={view==='evidence'?'selected':''} onClick={()=>setView('evidence')}>Evidence review</button></div>
 <div className="tracker-controls"><select aria-label="Score forecast sport" value={league} onChange={e=>{setLeague(e.target.value);setThreshold('all')}}><option value="all">All sports</option>{leagues.map(l=><option key={l}>{l}</option>)}</select><select aria-label="Forecast type" value={kind} onChange={e=>{setKind(e.target.value);setThreshold('all')}}><option value="all">All score forecasts</option><option value="total">Total score</option><option value="margin">Home winning margin</option><option value="both_score">Both teams score</option></select><select aria-label="Estimated probability filter" value={minimum} onChange={e=>setMinimum(e.target.value)}><option value="all">All probabilities</option><option value="60">60%+ estimated probability</option><option value="70">70%+ estimated probability</option><option value="80">80%+ estimated probability</option></select><select aria-label="Score forecast status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All records</option><option value="pending">Pending</option><option value="scored">Scored</option></select><select aria-label="Research threshold" value={threshold} onChange={e=>setThreshold(e.target.value)}><option value="all">All thresholds</option>{thresholds.map(t=><option key={t} value={t}>{t==='null'?'Both teams score':t}</option>)}</select><button className="outline" onClick={exportLedger} disabled={!data}>Export complete ledger</button></div>
 <p>{cohort.length} forecasts across {new Set(cohort.map(r=>r.event)).size} matches · multiple thresholds from one match are correlated.</p>
 {view==='forecasts'&&<><div className="outcome-grid">{rows.slice(0,limit).map(r=><button key={r.id} className="panel outcome-card" onClick={()=>setSelected(r)}><div className="live-event-top"><span className="tag">{r.league} · {r.kind.replace('_',' ')}</span><span className={`result ${r.result?r.result.correct?'positive':'incorrect':'pending'}`}>{r.result?r.result.correct?'WIN · Correct':'LOSS · Incorrect':'Pending'}</span></div><h2>{r.event}</h2><p>{new Date(r.starts_at).toLocaleString()}</p><div className="outcome-projection"><small>RESEARCH EVENT</small><strong>{r.description}: {r.predicted_outcome==='yes'?'Yes':'No'}</strong><b>{pct(r.estimated_probability)} <span>uncalibrated estimate</span></b></div><div className="outcome-evidence">{r.league_games} league results · home {r.team_games.home}, away {r.team_games.away} observed games</div>{r.evidence_warning&&<p>{r.evidence_warning}</p>}{r.result&&<p>Final score: {r.result.home_score}–{r.result.away_score}</p>}<div className="forecast-footer">Inspect fixed target and original record ↗</div></button>)}</div>
 {!rows.length&&<div className="empty live-empty"><h3>No forecasts match these filters yet</h3><p>The score model needs 20 observed league games and 5 per team. Collection must run long enough to build history. Past predictions are never fabricated.</p></div>}
 {rows.length>limit&&<button className="outline" onClick={()=>setLimit(limit+40)}>Show 40 more ({rows.length-limit} remaining)</button>}</>}
 {view==='evidence'&&<section className="panel"><h2>Evidence by sport, threshold and model</h2><p>Complete original cohorts, including losses. Probability filters above apply to cards and headline accuracy; this table retains all probabilities for comparison. Each row counts one forecast per match. Intervals describe observed accuracy, not future certainty.</p><div className="table-wrap"><table><thead><tr><th>SPORT / TARGET</th><th>MODEL</th><th>SCORED / MATCHES</th><th>ACCURACY / 95% INTERVAL</th><th>ESTIMATED / GAP</th><th>BRIER / LOG LOSS</th></tr></thead><tbody>{data?.evidence_report?.filter(r=>league==='all'||r.league===league).map(r=><tr key={r.league+r.target+r.model_version}><td>{r.league}<br/>{r.description}<br/>{r.status}</td><td>{r.model_version}</td><td>{r.metrics.scored} / {r.distinct_matches}</td><td>{pct(r.metrics.accuracy)}<br/>{r.metrics.accuracy_interval?`${pct(r.metrics.accuracy_interval[0])}–${pct(r.metrics.accuracy_interval[1])}`:'No scored evidence'}</td><td>{pct(r.mean_scored_probability)} / {pct(r.calibration_gap)}</td><td>{r.metrics.brier?.toFixed(3)??'—'} / {r.metrics.log_loss?.toFixed(3)??'—'}</td></tr>)}</tbody></table></div></section>}
 <details className="panel"><summary>Score-model exclusions and eligibility</summary>{data?.exclusions?.map((r,i)=><p key={i}>{r.league} · {r.event}: {r.reason}</p>)}{!data?.exclusions?.length&&<p>No current exclusion diagnostics. Check live collection status.</p>}</details><p className="research-note">Related targets from one match are correlated and are not independent evidence. Scores include provider overtime and NHL shootout scoring; unsupported penalty outcomes stay pending. Model inputs are observed final scores, not injury or website coefficients.</p>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Original score forecast" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="Close score forecast">×</button><h2>{selected.event}</h2><p>{selected.description}: {selected.predicted_outcome}</p><p>{selected.score_scope}</p><p>{selected.uncertainty}</p><p>Published {new Date(selected.published_at).toLocaleString()} · {selected.model_version}</p>{selected.empirical_frequency_interval&&<><h4>Historical team frequency interval</h4><p>{pct(selected.empirical_frequency_interval[0])}–{pct(selected.empirical_frequency_interval[1])}. Descriptive Wilson interval for observed frequencies; correlated matches and model error are not covered.</p></>}{selected.research_context&&<><h4>Research context frozen at publication</h4><p>{selected.research_context.numerical_use}</p>{Object.entries(selected.research_context.schedule_and_injuries).map(([side,c])=><p key={side}>{side}: {c.hours_since_prior_start??'Unknown'} hours since previous match start; injuries: {c.injury_coverage}</p>)}{selected.research_context.external_sources.map(ref=><p key={ref.url}><a href={ref.url} target="_blank" rel="noopener noreferrer">{ref.name}</a> · collected {new Date(ref.fetched_at).toLocaleString()} · {ref.use}</p>)}</>}<h4>Original probabilities</h4><pre>{JSON.stringify(selected.probabilities,null,2)}</pre><h4>Forecast SHA-256</h4><pre>{selected.hash}</pre><h4>Training SHA-256</h4><pre>{selected.training_data_hash}</pre></section></div>}
 </section>
}
